name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:   
      - uses: actions/checkout@v3
      - name: deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 10236
          local_path: '*'
          remote_path: '/root/triangulacja'
          delete_remote_files: true
          
      - name: run docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 10236
          script: |
            docker stop triangulacja
            docker rm triangulacja
            docker build -t triangulacja triangulacja/
            docker run --rm -d --name triangulacja -p 7777:5000 triangulacja
